# Generated by Django 2.2.5 on 2021-11-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='생일',
            field=models.DateField(blank=True, null=True),
        ),
    ]
