# Generated by Django 2.2.5 on 2022-02-08 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211206_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='언어',
            field=models.CharField(blank=True, choices=[('영어', 'en'), ('한국어', 'kr')], default='한국어', max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='통화',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('KRW', 'KRW')], default='KRW', max_length=3),
        ),
    ]
