# Generated by Django 2.2.5 on 2021-11-17 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_auto_20211117_2027'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amenity',
            options={'verbose_name_plural': '편의 시설'},
        ),
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': '부대 시설'},
        ),
        migrations.AlterModelOptions(
            name='houoserule',
            options={'verbose_name_plural': '사용 규칙'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name_plural': '방 타입'},
        ),
        migrations.AlterField(
            model_name='room',
            name='부대시설',
            field=models.ManyToManyField(blank=True, to='rooms.Facility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='사용규칙',
            field=models.ManyToManyField(blank=True, to='rooms.Houoserule'),
        ),
        migrations.AlterField(
            model_name='room',
            name='편의시설',
            field=models.ManyToManyField(blank=True, to='rooms.Amenity'),
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80)),
                ('file', models.ImageField(upload_to='')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
