# Generated by Django 2.2.5 on 2021-11-25 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20211117_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='방종류',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_types', to='rooms.RoomType'),
        ),
        migrations.AlterField(
            model_name='room',
            name='부대시설',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Facility'),
        ),
        migrations.AlterField(
            model_name='room',
            name='사용규칙',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Houoserule'),
        ),
        migrations.AlterField(
            model_name='room',
            name='주인장',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='편의시설',
            field=models.ManyToManyField(blank=True, related_name='rooms', to='rooms.Amenity'),
        ),
    ]
