# Generated by Django 2.2.5 on 2021-11-25 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20211125_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='방종류',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rooms', to='rooms.RoomType'),
        ),
    ]
